name: "Transport for Ireland GTFS"
description: "Home Assistant Addon that provides real-time  GTFS-R information from Transport from Ireland via a REST API."
version: "1.1.12"
slug: "gtfs_tfi"
init: false
webui: http://[HOST]:[PORT:6824]/upcoming.json
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  6824/tcp: 6824
options:
  primary_api_key: null
  secondary_api_key: null
  stop_1_id: null
  stop_2_id: x
  stop_3_id: x
  stop_4_id: x
schema:
  primary_api_key: str
  secondary_api_key: str
  stop_1_id: str
  stop_2_id: str
  stop_3_id: str
  stop_4_id: str
